### PR TITLE
Properly fix #2057 by asking tiny remapper to patch package access

### LINKED ISSUE #2057: NoiseChunkGenerator should be in net.minecraft.world.gen
```
java.lang.IllegalAccessError: class net.minecraft.world.gen.chunk.NoiseChunkGenerator tried to access protected method 'double net.minecraft.world.gen.StructureWeightSampler.getWeight(int, int, int)' (net.minecraft.world.gen.chunk.NoiseChunkGenerator and net.minecraft.world.gen.StructureWeightSampler are in unnamed module of loader 'app')
```

While I think the package for `NoiseChunkGenerator` is currently better, running Minecraft in a development environment causes this crash.

### PR DESCRIPTION
**Pull request by liach**
Needs a loom pr as well. The loom pr can properly fix the problem
in dev env.

Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by liach** [comment]
@Chocohead Thank you for your suggestion from https://github.com/FabricMC/yarn/issues/2057#issuecomment-778848695

**Comment by modmuss50** [comment]
No, this shouldn’t be used in loom as it will change it for mods compiling. I wouldn’t change it here either as there is no need to it will just cause added confusion between the two envs

**Comment by liach** [comment]
then should yarn output like an access widener alongside mappings indicating members that need widening? or what approach do you suggest?

**Comment by modmuss50** [comment]
I suggest we dont touch it. Mod dev envs should not have mapping specific access wideners as we would need to bake them into each mod.

Even we if fix all of the package access issues it will need to stay as it will break when an update comes along and adds a new class.

**Comment by liach** [comment]
> I suggest we dont touch it. Mod dev envs should not have mapping specific access wideners as we would need to bake them into each mod.
> 
> Even we if fix all of the package access issues it will need to stay as it will break when an update comes along and adds a new class.

so you suggest keeping the status quo, which i agree. and we leave the handling to loader exclusively?

**Comment by modmuss50** [comment]
Yes. 

I think mixin does complain a little in the log. I wouldn’t be against removing that log line though.

**Comment by liach** [comment]
Hmm, should we add to tiny v2 metadata that some namespaces needs package access checks?
I mean, we can add extra metadata like `\tpackage-access-checks\tfalse\ttrue` etc. the values are tab split and each value indicates if each namespace may have package access issues

**Comment by liach** [comment]
Closing in favor of https://github.com/FabricMC/tiny-remapper/issues/46

**Pull request closed without merging**
