### PR TITLE
Rename Entity#inanimate

### LINKED ISSUE #2920: Entity.inanimate field named incorrectly
The `Entity.inanimate` (`field_23807`) is named incorrectly; it means if an entity should be considered for shape intersection calculation, which is its exclusive usage. Discovered while reviewing #2903.

### PR DESCRIPTION
**Pull request by apple502j**
Fixes #2920

### CODE REVIEW

**Review by liach — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Comment by Shnupbups** [comment]
Hmm, wouldn't the word intersectable imply that things *can* intersect it? As in, that blocks *can* be placed within it, and mobs *can* spawn within it? Whereas this boolean does the opposite.

**Comment by apple502j** [comment]
Uhh... please suggest a better name :tiny_potato:

**Review by enbrain — APPROVED** [review]

**Comment by apple502j** [comment]
Closing - `intersectable` is not the right word. But not sure what to name this.

**Comment by liach** [comment]
Hmm, so like `spawnBlocking`? Or `blocking` as such entities block block placing and entity spawning?

**Comment by apple502j** [comment]
Okay, reopening

**Comment by apple502j** [comment]
Renamed to `intersectionChecked` - `spawnBlocking` is inaccurate, and `blocking` might be used somewhere else to mean other stuff - e.g. shields.

**Review by Shnupbups — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
