### PR TITLE
Update missing Items mappings

### PR DESCRIPTION
**Pull request by doublej472**
This PR adds some of the missing mappings in the Items class

### CODE REVIEW

**Review by asiekierka — APPROVED** [review]

**Review by kashike — APPROVED** [review]

**Comment by doublej472** [comment]
@asiekierka @kashike I've added a much bigger commit marking the Enigma names as unobfusicated (which was surprisingly annoying to do), please let me know what you think!

**Comment by asiekierka** [comment]
@doublej472 if they're dark gray *don't touch them* unless they need corrections - they're auto-derived

**Comment by doublej472** [comment]
@asiekierka alright, I've removed that part of the PR now.

It did fix the generated code from `Export Source...` in yarn, otherwise it uses the obfusicated name, maybe an Enigma bug / feature?

**Comment by asiekierka** [comment]
The Enigma source code export isn't all that great - using fabric-loom (or, in other words, applying Fernflower (or Procyon, or CFR) to a tiny-remapper-remapped JAR) is by far preferable. Either way, decompiled source code should only be used as a lookup aid and not recompiled due to the chances of decompiler artifacts causing different behaviour.

**Review by NeunEinser — APPROVED** [review]

**Pull request merged**
