### PR TITLE
Flesh out several "list" classes

### PR DESCRIPTION
**Pull request by SquidDev**
I realise this is very low-hanging fruit, but it was bugging me and it sorta makes some deobfuscated sources easier to understand.

 - Some fields of `Material`
 - `Blocks`
 - `Items` (and some item classes)
 - Some fields in `BlockSoundGroup`
 - `Stats`
 - `RecipeSerializers`
 - `StatusEffects`

### CODE REVIEW

**Comment by Prospector** [comment]
hey, someone had to do the lowhanging fruit. However note that the status effects and stats should be mapped by asie's thing automatically in dev envs, just not in pomf yet

**Review by jamierocks — APPROVED** [review]
Wow!

Though you should've mentioned this in IRC - there is WIP tooling to automatically do this sort of work.

**Review by Prospector — APPROVED** [review]

**Comment by SquidDev** [comment]
Ahhh, neat! I remember asie mentioning something, but wasn't sure how far along it was.

**Comment by asiekierka** [comment]
``` However note that the status effects and stats should be mapped by asie's thing automatically in dev envs, just not in pomf yet```

Yes, we're generally not merging that and it should be dropped from the PR. particularly Blocks and Items and the other ones with string-based registries.

**Pull request closed without merging**
