### PR TITLE
Use automapped names for documented fields

### LINKED ISSUE #1493: GameRules automatic mapping is broken due to #1381
## Issue
Fields of [net/minecraft/world/GameRules](https://github.com/FabricMC/yarn/blob/779b1dc2f52747784d4ee61b2683c53eac5360c3/mappings/net/minecraft/world/GameRules.mapping) was mapped automatically (from strings), but in #1381 documentation was added **without names** and mappings are not longer applied automatically.

### Expected behaviour
Mapping names should automatically be named (if possible) from strings without `FIELD` nor `COMMENT` notation at all.

### Yarn version:
1.16-rc1+build.4 _(latest atm)_

### How it looks in `.mapping` file
image
### The names are not detected automatically
image
### In the library and generated sources there is no names too:
image

### PR DESCRIPTION
**Pull request by YanisBft**
The latest version of Enigma fixes javadocs on automapped fields (thanks 2xsaiko)
Closes #1493

### CODE REVIEW

**Review by liach — APPROVED** [review]
Just remember to update filament version in `build.gradle`.

**Review by haykam821 — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Comment by modmuss50** [comment]
I plan to merge this after validating the diff of the output, sorry I havent had a chance to do so just yet, its not forgotten 👍

**Comment by modmuss50** [comment]
Please let me know if this breaks anything. 👍

**Comment by haykam821** [comment]
This has caused affected fields to be unmapped.

**Comment by modmuss50** [comment]
Will revert it in a bit, was my bad for not actually checking it.

**Comment by liach** [comment]
Hmm, that should be a stitch bug then.

**Pull request merged**
