### PR TITLE
Map 56 fields in the grindstone block

### PR DESCRIPTION
**Pull request by Prospector**
:mojank:

this is like 7% of the missing field names currently lol

### CODE REVIEW

**Review by Shnupbups — APPROVED** [review]

**Comment by Shnupbups** [comment]
k

**Review by i509VCB — APPROVED** [review]
👀

**Review by shedaniel — COMMENTED** [review]
i will assume that this is accurate

**Review by shedaniel — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Review by vini2003 — APPROVED** [review]
after very thorough review i say good to go

**Comment by i509VCB** [comment]
For info, in modmuss's stream, prospector said he made a block to test this and just disabled things to figure it out.

**Review by Ueaj-Kerman — APPROVED** [review]

**Comment by Prospector** [comment]
block https://gist.github.com/Prospector/277834ff6b967d61968f59aa6589eea3

**Review by liach — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]
Awesome work

**Pull request merged**
