### PR TITLE
fix visibility issues

### PR DESCRIPTION
**Pull request by NeunEinser**
Fixes most of #683 
Not fixed:
```
ERROR: Must be in one package:
net/minecraft/client/gui/MapRenderer
net/minecraft/client/gui/MapRenderer$1
net/minecraft/client/gui/MapRenderer$MapTexture
net/minecraft/client/network/ClientPlayNetworkHandler
net/minecraft/client/network/ClientPlayNetworkHandler$1
net/minecraft/client/network/PlayerListEntry
net/minecraft/client/network/PlayerListEntry$1
```
I think this is a false positive. Their obfuscated names are very far apart.

This pull request adopts the package structure for gui screens from #649.
I used `ingame` for what Rune called `inventory` in #649, because there are screens in there that are not inventory related, like command block screens, and book (edit) screen. Not sure about that one, though, since there are also screens that are in separate packages, like the PauseMenuScreen. Most ingame screens are in that package, though
Also changes some names where they were bad.

### CODE REVIEW

**Comment by NeunEinser** [comment]
Requesting review from @JamiesWhiteShirt to confirm my branch fixes the visibility issues and does not create new ones somehow.

**Comment by liach** [comment]
The so called map renderer is in fact a client map manager, hence it qualifies for the network package.

**Review by Runemoro — APPROVED** [review]

**Review by Gegy — APPROVED** [review]

**Comment by JamiesWhiteShirt** [comment]
I can confirm that the partition that was not fixed is likely a false positive. There is a chance we are missing some of them, but these are definitely great to have fixed now.

**Comment by liach** [comment]
It is not a false positive, given the client network handler accesses `MapRenderer$MapTexture`, which is package private. It is totally possible that mojang has two same packages in two different modules.

**Comment by NeunEinser** [comment]
> It is not a false positive, given the client network handler accesses `MapRenderer$MapTexture`, which is package private.

From Discord (by `@JamiesWhiteShirt#8888`) (I didn't really check myself)
>MapRenderer has a public method that returns a package-private which I had not accounted for. this is apparently legal in java land
>and a public method with a package-private parameter
>so the descriptor of the called method doesn't matter

So `MapTexture` is the return type of a public method, which is apparently legal.

>It is totally possible that mojang has two same packages in two different modules.

While this is theoretically possible, looking at the context and other classes and packages in between, it is highly unlikely that these are in different modules.

**Pull request merged**
