### PR TITLE
framebuffer, screenshots, gl info

### PR DESCRIPTION
**Pull request by liach**
FixedDataSetter -> GlInfoConsumer
ScreenshotUtils -> Screenshooter (no longer a utility class)

### CODE REVIEW

**Review by enbrain — APPROVED** [review]

**Review by Player3324 — APPROVED** [review]

**Comment by liach** [comment]
@OroArmor Since I see you wondering about the rename, here's the reason :point_up: it is no longer a utility class but an object class

**Comment by OroArmor** [comment]
ah ok. i didnt know its functionality changed

**Comment by liach** [comment]
Feel free to suggest a better name for `Screenshooter`.

Fyi, it holds a few utility methods for regular screenshots and panoramas; it is used as an object only for taking ultra-detailed raster images, which is available through a method in `MinecraftClient` that is not used anywhere in vanilla code, like the method for taking panorama. Any ideas?

**Comment by haykam821** [comment]
I would suggest `ScreenshotRenderer` if the main ability is to render screenshots without necessarily writing them to a file, and otherwise `ScreenshotHelper`.

**Comment by i509VCB** [comment]
Enlightened name imo would just be `Screenshot`.

Given a class named `Screenshot` I'd think that `finish` could become `take` since you take a screen shot.

**Comment by liach** [comment]
Hmm, I think another way to name this is to look back at the `MinecraftClient` method that uses this. The data comes from some gl call, and I recall that gl call has a descriptive name, and was more concise than `screenshot`

**Pull request merged**
