### PR TITLE
Consistent 3F and 4F suffix usage

### LINKED ISSUE #3838: Inconsistent underscores in fields named after the Vector3f class
- `TrackedDataHandlerRegistry.VECTOR3F`
- `PacketCodecs.VECTOR3F`
- `Codecs.VECTOR_3F`

### PR DESCRIPTION
**Pull request by Octol1ttle**
Fixes #3838

### CODE REVIEW

**Review by apple502j — APPROVED** [review]

**Comment by haykam821** [comment]
Should the underscore variant be used instead? To me, 'vector 3f' feels more clear than 'vector3f'.

**Comment by Octol1ttle** [comment]
> Should the underscore variant be used instead? To me, 'vector 3f' feels more clear than 'vector3f'.

@apple502j @Shnupbups thoughts?

**Comment by Juuxel** [comment]
I'd say the underscore forms like `VECTOR_3F` are more readable.

**Comment by Shnupbups** [comment]
I think I agree, underscores are more readable

**Review by Juuxel — APPROVED** [review]

**Review by haykam821 — APPROVED** [review]

**Pull request merged**
