### PR TITLE
isMinceraft

### PR DESCRIPTION
**Pull request by shedaniel**
From #mod-dev in fabricord

Thanks ramidzkh
https://discordapp.com/channels/507304429255393322/507982478276034570/629231365732433930

### CODE REVIEW

**Comment by natanfudge** [comment]
isMinceraft

**Review by natanfudge — APPROVED** [review]

**Review by ramidzkh — APPROVED** [review]
`isMinceraft` is probably the most appropriate name.

**Review by modmuss50 — APPROVED** [review]

**Comment by Runemoro** [comment]
There's a spelling mistake in the name... Also, what does this do...?

**Comment by Pyrofab** [comment]
Can you really not guess ?

**Comment by modmuss50** [comment]
https://minecraft.gamepedia.com/Menu_screen#Minceraft

**Comment by liach** [comment]
This should have been `minceraft` given this is a field instead of a boolean getter method

**Comment by natanfudge** [comment]
Is that the convention? I would use isX for fields still.

**Comment by liach** [comment]
In general, use adjective (phrases) for boolean fields, noun (phrases) for other fields, and verb (phrases) for methods.

```java
public void setFat(boolean fat) {
  this.fat = fat;
}
```
looks way better than 
```java
public void setIsFat(boolean isFat) {
  this.isFat = isFat;
}
```

**Comment by natanfudge** [comment]
I would call it `setFat` even if the field is named `isFat`. The setter method should really only be in relation to the getter method because the field is an implementation detail.

**Comment by liach** [comment]
`this.isFat = false` just doesn't make sense
and it doesn't make sense either when you have field name same as the method name
Why bother having `is` prefix when you can get rid of it?

**Comment by natanfudge** [comment]
> Why bother having is prefix when you can get rid of it?

`isFat` is distinguishable as a boolean, while `fat` could easily be an int (20 mg of fat).

**Comment by liach** [comment]
For example, when something like spring/gradle generates code, they do such:
E.g. you have
```
boolean isFat();
```
in the code gradle buildscript use
and you can call `sth.fat` to effectively call `isFat()` method in your gradle buildscript

This is the convention. This is effective. 

Your argument may apply for `fat` as it has a noun meaning, but not so much for `beautiful` which is exclusively an adjective.

**Comment by shedaniel** [comment]
After a quick look at CONVENTIONS.md (Or whatever it is called I am on mobile) I guess I am happy to change it, but naming it `minceraft` only also doesn’t make sense, as it is still not an adjective (phrase).

**Comment by liach** [comment]
`easterEggActive`?

**Comment by shedaniel** [comment]
I wouldn’t know what that is until someone tell me though

**Comment by natanfudge** [comment]
> For example, when something like spring/gradle generates code, they do such:
E.g. you have
boolean isFat();
in the code gradle buildscript use
and you can call sth.fat to effectively call isFat() method in your gradle buildscript


Funny you should mention that, Kotlin does it my way.
https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters

As Daniel has said mincecraft is a noun.

**Comment by liach** [comment]
`minceraftShown`

**Pull request merged**
