### PR TITLE
ServerWorldAccess -> StructureWorldAccess

### PR DESCRIPTION
**Pull request by i509VCB**
This describes with more detail what this specific interface is.

### CODE REVIEW

**Comment by YanisBft** [comment]
What about `PostStructuresWorldAccess` or `StructureGeneratedWorldAccess`?

**Comment by liach** [comment]
I agree with yanis. a naming like `XxxWithStructures` would sounds like `Strutures` while it is a world access.

**Comment by Player3324** [comment]
The withXY name is supposed to declare the additional feature, Post* or StructureGenerated* can be misunderstood and implies some temporal relation that doesn't exist. Maybe something like *CapableWA or *ProvidingWA would work too.

It is also important to note that these are very special purpose interfaces, so more descriptive naming should be chosen over "nicer" names.

**Comment by liach** [comment]
Then `StructurePopulatedWorld`, no need for `Access` part of name at least

**Comment by Player3324** [comment]
That is wrong though, there are plenty of world-like classes that have structures populated without this interface.

**Comment by liach** [comment]
Maybe `StructureAvailableWorld`? mojang is known for creating interfaces to restrict operations, like for text, so they don't need a state machine but just passing restricted interfaces for operational safety?

**Comment by Player3324** [comment]
The structures are "available" (as in present) regardless of the interface - they are part of the world once generated. We need to talk about structure (meta)data I think.

**Comment by liach** [comment]
> The structures are "available" (as in present) regardless of the interface

Well, this is exactly the same case in `Text`. Text implementations are regardless mutable. However, mutation operations are only exposed via the `MutableText` interface. Maybe they pass in this interface than a full `ServerWorld` to indicate that at where this interface is used, the operations this interface support is totally safe while other operations may not be guaranteed.

**Comment by Player3324** [comment]
That's not what I mean, structures can be understood as just the blocks placed into the world. The client-side world has them, but not this interface. Your names imply otherwise with this fairly reasonable interpretation.

**Comment by liach** [comment]
> structures can be understood as just the blocks placed into the world

no? structure has quite a few extra attached information afaik that is used by other world generation components. the thing called structure that is part of world generation is only safely accessible when this interface is provided.

**Comment by Player3324** [comment]
That doesn't matter, some people will think of structures as I said, making the names insufficiently descriptive.

**Review by YanisBft — APPROVED** [review]
WorldAccessWithStructures is not that bad afterall (didn't want to start a bikeshedding lol, I'm fine with this name)

**Comment by Runemoro** [comment]
`StructureView`

**Comment by i509VCB** [comment]
🚲🏠

Rune I think it's been discussed before that WorldAccess and above interfaces aren't views in the typical sense. Also this is a very specific interface for a specific purpose, Player has said he wants more descriptive names for these very niche interfaces.

**Comment by Prospector** [comment]
Is it really niche? Don't like loads of the features use this as a parameter? ServerWorldAccess seems good to me still.

**Comment by Runemoro** [comment]
> WorldAccess and above interfaces aren't views in the typical sense

What's the difference between an access and a view? I thought we got rid of `Access` and renamed everything to `View`.

In any case, my problem is not with the word `Access`, but with the word `With`. It could be `StructureAccess` or `StructureWorldAccess` and mean the same thing with one word less.

**Comment by i509VCB** [comment]
WorldAccess was added originally to get rid of the last yarn name that violated the naming standards, that name alone was a fucking nightmare to decide on. I'd be open to discussing the merits of keeping which names. I'd definitely say we are also somewhat restricted in naming because of the actual World classes (and no one wanting WorldWithXyz)

**Comment by Runemoro** [comment]
> no one wanting WorldWithXyz

In every single case, `WorldWithXyz` should be `XyzWorld`. More generally, it's a common Java convention to use `XyzAbc` instead of `AbcWithXyz`.

**Comment by liach** [comment]
> In every single case, `WorldWithXyz` should be `XyzWorld`. More generally, it's a common Java convention to use `XyzAbc` instead of `AbcWithXyz`.

This is literally the whole point of my argument. This thing would look like some type of "structures" on first sight while it is actually a world

**Comment by jaskarth** [comment]
I would also vote for `StructureWorldAccess`, as `StructuresAccess` doesn't immediately convey that it's a world.

**Comment by YanisBft** [comment]
+1 for `StructureWorldAccess`

**Comment by i509VCB** [comment]
Now `StructureWorldAccess`

**Review by liach — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Review by Runemoro — APPROVED** [review]

**Review by Player3324 — APPROVED** [review]
better than before :D

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
