### PR TITLE
Blocks, Entities, Models

### PR DESCRIPTION
**Pull request by Darkhax**
Adds some more mappings for blocks, entities and entity models.

### CODE REVIEW

**Comment by Prospector** [comment]
Hmm I'm not a fan of `minecraftGame`. Feels quite long. I'd probably do either `mc`, `minecraft`, or just `game`

**Comment by lclc98** [comment]
Yeah minecraftGame was me, I didn't know what people usually called it

**Comment by asiekierka** [comment]
The usual name I use is "mc", but "game" could work just as well.

**Comment by Prospector** [comment]
I always use `mc` as well, but I do kinda like the sound of `game`.

**Review by asiekierka — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
