### PR TITLE
Misc Hit Result stuff

### PR DESCRIPTION
**Pull request by shadowfacts**
I'm not entirely certain about `isSideInverted`, but the only usage of it is in ScaffoldingItem::getPlacementContext:

```java
if (itemPlacementContext.isPlayerSneaking()) {
    direction6 = (itemPlacementContext.isSideInverted() ? itemPlacementContext.getFacing().getOpposite() : itemPlacementContext.getFacing());
}
```

### CODE REVIEW

**Comment by asiekierka** [comment]
But where is it *set* and in what context?

**Comment by shadowfacts** [comment]
- defaulted to false in the BlockHitResult constructor
- false in BlockHitResult::createMissed
- false in BoundingBox.a(Iterable, Vec3d, Vec3d, BlockPos)
- false in Bootstrap.b constructor
- false in ItemPlacementContext.create
- false in arz.a(Entity, boolean, boolean, Entity)
- **true in VoxelShape.rayTrace**

**Comment by asiekierka** [comment]
IMO just drop the mapping for now so we can merge

**Comment by shadowfacts** [comment]
Reverted.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
