### PR TITLE
BlockBreakParticle mapping (test)

### PR DESCRIPTION
**Pull request by natanfudge**
- net/minecraft/client/particle/BlockCrackParticle -> net/minecraft/client/particle/BlockBreakParticle  
  - It's the little pieces that get thrown around, not the crack.

### CODE REVIEW

**Comment by natanfudge** [comment]
It works \o/

**Comment by liach** [comment]
the vanilla's piece particle's was called icon crack. that's its origin.

**Comment by liach** [comment]
Imo we need a vote on this. I personally am against this proposal.

**Comment by liach** [comment]
@natanfudge In `ParticleManger#registerDefaultFactory`, the class is linked with `block` particle type, so `BlockParticle` may be better.
image

**Comment by natanfudge** [comment]
It's now `BlockDustParticle`.

**Review by liach — CHANGES_REQUESTED** [review]
:angry:
image

**Comment by natanfudge** [comment]
Oh sorry!

**Review by liach — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
