### PR TITLE
some things

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Review by jamierocks — APPROVED** [review]
:+1:

**Comment by Prospector** [comment]
We're gonna need a script or something to convert all the `game` fields to `client`. There's got to be hundreds

**Comment by jamierocks** [comment]
That could be done through Survey's mapping capabilities rather easily. See https://github.com/FabricMC/pomf/pull/175#issue-226629020 and https://gist.github.com/jamierocks/f953f7ba01a3556ad49cc25d97efb505#file-mapper-json-L46-L57 :)

**Review by modmuss50 — APPROVED** [review]
Looks great, nice work.

**Pull request merged**
