### PR TITLE
Map tracked position stuff in Entity

### PR DESCRIPTION
**Pull request by Leo40Git**
Changes:
- `private Vec3d field_25750` -> `private Vec3d trackedPosition`
- `public void method_30228(Vec3d arg)` -> `public void updateTrackedPosition(Vec3d pos)` (based on its overload `public void updateTrackedPosition(double, double, double)`)
- `public Vec3d method_30227()` -> `public Vec3d getTrackedPositon()`

### CODE REVIEW

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
Just curious, what is this tracked position used for and where is it updated?

**Comment by Leo40Git** [comment]
Possibly something to do with syncing entities from server to client, considering the getter is client-only.

**Comment by liach** [comment]
interesting. I wonder what packet syncs it

**Review by YanisBft — APPROVED** [review]

**Comment by Leo40Git** [comment]
Methods of interest in `EntityS2CPacket`:
- `public Vec3d method_30302(Vec3d arg)` - takes a `Vec3d`, returns a `Vec3d` offset by the `delta*` fields, possible name `calculateDeltaPosition`?
- `public double method_30301(long arg)` - seems to be the reverse of `encodePacketCoordinate`, possible name `decodePacketCoordinate`?

**Pull request merged**
