### PR TITLE
Name color channel helper methods in NativeImage

### PR DESCRIPTION
**Pull request by kb-1000**

### CODE REVIEW

**Comment by liach** [comment]
maybe just extractXxx than extractXxxChannel? that seems confusing when i see writeToChannel

**Comment by falseresync** [comment]
maybe `getRed`, `writeToChannel` & `asInt`?

**Comment by liach** [comment]
I agree with `getRed` and `writeToChannel`. `asInt` is too generic and isn't very indicative on how 4 ints are converted to one; `packColor` would be better, and the `Int` suffix is not necessary imo.

**Comment by YanisBft** [comment]
Closing this as this class is mapped as of f80e52b. Please reopen and update this PR if you want to backport the mappings in 1.15.2.

**Pull request closed without merging**
