### PR TITLE
TACS 2

### PR DESCRIPTION
**Pull request by Gegy**
TACS 1 was so good that they made TACS 2

### CODE REVIEW

**Review by LambdAurora — APPROVED** [review]

**Review by jaskarth — COMMENTED** [review]
This is epic

**Review by jaskarth — APPROVED** [review]

**Comment by kvverti** [comment]
Is this actually the entity storage class? And is there an `AbstractThreadedAnvilStorage` somewhere?

**Comment by i509VCB** [comment]
Okay so to ask the question. What proof shows that the class should be TAES.

**Comment by jaskarth** [comment]
the code

**Review by YanisBft — APPROVED** [review]
tacs you so much

**Comment by kvverti** [comment]
Sorry I've just named it `ServerEntityManager`

**Comment by hYdos** [comment]
bad. Gegy's name was better. please reopen

**Pull request closed without merging**
