### PR TITLE
StateFactory$Builder with -> append

### PR DESCRIPTION
**Pull request by ChloeDawn**
The term `append` makes more sense for a mutable Builder type

### CODE REVIEW

**Comment by liach** [comment]
How about add which is more concise

**Comment by ChloeDawn** [comment]
Hmm, that works too. I was thinking more about objects such as `StringBuilder`, but I guess `add` is appropriate too as it is the term Guava uses for appending to immutable collection builders, which is what this builder effectively is

**Comment by modmuss50** [comment]
add isnt a bad idea.

**Comment by ChloeDawn** [comment]
Updated

**Review by liach — APPROVED** [review]

**Review by NeunEinser — APPROVED** [review]

**Review by Gegy — APPROVED** [review]

**Pull request merged**
