### PR TITLE
Move the ScreenTexts class to the net.minecraft.screen package

### LINKED ISSUE #3112: ScreenTexts is no longer client-side only
This is referenced by `SignBlockEntity` and used server-side.

### PR DESCRIPTION
**Pull request by haykam821**
Fixes #3112

### CODE REVIEW

**Review by enbrain — APPROVED** [review]

**Comment by apple502j** [comment]
I believe this should be moved to `net.minecraft.text` instead.

**Comment by haykam821** [comment]
@apple502j I disagree as this class is still clearly related to screens; for example, the text fields are used for common components of a GUI. Otherwise, it would just be a second `Texts` class.

**Comment by apple502j** [comment]
Hmm, then maybe it's fine to keep it at screen package.

**Comment by Juuxel** [comment]
I'd say either package is fine - this is related to both after all. `text` might be a bit more natural though since the `screen` package mostly deals with screen handlers.

**Comment by apple502j** [comment]
Should we have a vote for this？

**Comment by liach** [comment]
I think this is just some general ui prompt text. It probably works better in screen package as it's not core text infrastructure, but we can consider renaming the class as well.

**Review by Juuxel — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Review by liach — APPROVED** [review]

**Pull request merged**
