### PR TITLE
Improve ChunkStatus mappings

### PR DESCRIPTION
**Pull request by jakobkmar**

### CODE REVIEW

**Comment by liach** [comment]
Hmm, you renamed non-obfuscated members, which we don't usually do and aren't sure of its safety (should be handled by remappping though)

**Comment by jakobkmar** [comment]
which members where non-obfuscated?

**Comment by liach** [comment]
The 3 "doWork" methods that appear red but are actually just straight from mojang names. It's said to be a bug in proguard that they don't obfuscate these if these methods are used by lambda metafactories.

**Comment by jakobkmar** [comment]
I will revert the two mappings of `doWork` as soon as I have access to my PC again.

Also, is it okay that I remapped `function` to `convertCallback` or is that one a ProGuard compiler bug and non-obfuscated as well?

**Comment by liach** [comment]
Naming any parameter is fine; those red names are not always there but only suggested by enigma.

**Comment by jakobkmar** [comment]
I reverted the mappings for the `doWork` functions.

**Review by liach — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Pull request merged**
