### PR TITLE
Realm mappings

### PR DESCRIPTION
**Pull request by Runemoro**
These are all Mojang names. The PR was created using Matcher to match the names of the last unobfuscated Realms jar (1.14.5) with the current names.

### CODE REVIEW

**Comment by modmuss50** [comment]
Thoughts on changing the package to be in net.minecraft?

Now that it’s in the main jar I see no reason for it to be in it’s own separate package.

**Comment by Runemoro** [comment]
We have classes which are not obfuscated in the `com.mojang.realmsclient.dto` package.

**Comment by asiekierka** [comment]
The package is fine.

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Anyone else got any further input on this?

**Review by Chocohead — APPROVED** [review]

**Review by quat1024 — APPROVED** [review]
We should just merge this to get realms out of intermediary land, and sort out any problems later

**Review by liach — APPROVED** [review]

**Review by Blayyke — APPROVED** [review]

**Pull request merged**
