### PR TITLE
Rename tick scheduling methods

### LINKED ISSUE #3161: Rename WorldAccess#createAndScheduleBlockTick
First, sorry for causing this mess.

When I mapped this in 1.18 snapshots I did not realize how often this method was used. The name is very long for a simple method. It doesn't feel very yarn-y. Maybe mapping stuff at 4AM didn't work.

I propose renaming this to `scheduleBlockTick`. This is very impactful, but I think this needs to be renamed.

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #3161 
Very impactful, should be merged asap if we want to get this to 1.19

### CODE REVIEW

**Review by haykam821 — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Review by Shnupbups — APPROVED** [review]

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
@modmuss50 Anything wrong with this?

**Comment by haykam821** [comment]
I don't see anything wrong with this pull request, but since Minecraft 1.19 has been released, it being merged will have to wait until the next snapshot cycle starts.

**Review by modmuss50 — APPROVED** [review]

**Review by Player3324 — APPROVED** [review]

**Comment by liach** [comment]
Hmm, so is there anyone using yarn as a dependency in `build.1+` version format? If no, then I'd argue fixing such names is no big problem, as people only bump mappings voluntarily, meaning they understand that some names they use will change, for the better or (unfortunately) worse.

**Comment by liach** [comment]
Should we aim for 1.19.1 since this has been a 'big' update?

**Comment by apple502j** [comment]
@liach Unsure. Almost all changes are to chat and networking stack plus some allay changes, there are little to no changes required for others.

**Comment by apple502j** [comment]
Would like to have this land in 1.19.3.

**Review by enbrain — APPROVED** [review]

**Pull request merged**
