### PR TITLE
Produce TinyV2 mappings 

### PR DESCRIPTION
**Pull request by natanfudge**
This PR requires the following PRs in order:
- FabricMC/tiny-mappings-parser#3
- FabricMC/Enigma#164
- FabricMC/stitch#15
- FabricMC/intermediary#10

### CODE REVIEW

**Comment by modmuss50** [comment]
This should not remove v1 mappings, v2 mappings should be generated alongside the v2 mappings.

**Comment by natanfudge** [comment]
OK, it works quite a bit differently now.

**Comment by liach** [comment]
@natanfudge might consider looking into FabricMC/fabric-mixin-compile-extensions#2 as well.

**Comment by natanfudge** [comment]
I'm closing this one in favor of #914 because I fucked something up (see "unknown repository" as head)

**Pull request closed without merging**
