### PR TITLE
lots of world gen mappings

### PR DESCRIPTION
**Pull request by valoeghese**

### CODE REVIEW

**Comment by valoeghese** [comment]
review this pls

**Comment by liach** [comment]
@valoeghese compare to #905 
also please move block state providers etc to a new package

**Comment by valoeghese** [comment]
hmm

**Comment by valoeghese** [comment]
I'll move block state providers to another package

**Comment by valoeghese** [comment]
other than that I don't want to make this pr bigger

**Comment by valoeghese** [comment]
Moved state providers to a new package

**Review by YanisBft — APPROVED** [review]

**Comment by liach** [comment]
Btw did you look at what the dynamic writes/reads when you map the names for these feature configs? there are some insightful names and some bad names there

**Review by Runemoro — APPROVED** [review]

**Review by liach — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
