### PR TITLE
Map the new 1.14 classes

### PR DESCRIPTION
**Pull request by Runemoro**

### CODE REVIEW

**Comment by asiekierka** [comment]
Could also handle BlockPattern$c while at it... that's the *other* new class

**Review by modmuss50 — APPROVED** [review]
im happy with this, can map the other class if you want.

**Comment by Runemoro** [comment]
> Could also handle BlockPattern$c while at it... that's the other new class

Mapped it too.

**Review by modmuss50 — APPROVED** [review]
Changes look good to me

**Pull request merged**
