### PR TITLE
Fix clash of CommandBlockBlockEntity#getType with BlockEntity#getType

### PR DESCRIPTION
**Pull request by NeunEinser**

### CODE REVIEW

**Comment by NeunEinser** [comment]
Should I also submit this to the 1.14.4 branch?

**Comment by liach** [comment]
yes please

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
does this clash exist for cmd block minecarts?

**Review by Juuxel — APPROVED** [review]

**Comment by liach** [comment]
So this is apparently the only instance of such clash left. Good.

**Review by JamiesWhiteShirt — APPROVED** [review]

**Pull request merged**
