### PR TITLE
Map two methods in GeneratorType

### PR DESCRIPTION
**Pull request by YanisBft**

### CODE REVIEW

**Comment by liach** [comment]
Hmm, what exactly is `first biome`?

**Comment by YanisBft** [comment]
> Hmm, what exactly is `first biome`?

It gets the first biome in the biome list of biome source

**Review by liach — APPROVED** [review]

**Comment by Gegy** [comment]
Hm, how is the first biome value used? Is it used in some more specific context, or is it totally arbitrary?

**Comment by YanisBft** [comment]
> Hm, how is the first biome value used? Is it used in some more specific context, or is it totally arbitrary?

It's used when generating buffet worlds to get the only biome

**Review by Gegy — APPROVED** [review]

**Pull request merged**
