### PR TITLE
Unmap mojang named methods and fields

### PR DESCRIPTION
**Pull request by modmuss50**
We might give these intermediary names in future snapshots, for now this should prevent any issues.

This shouldn't break current as they are given the mojang name and not the yarn name.

### CODE REVIEW

**Comment by Chocohead** [comment]
Is it intensional this doesn't remove all of the Mojang named things (like the fields in `Screen`)?

**Comment by LemmaEOF** [comment]
This is specifically about deobf'd Mojang names, iirc.

**Comment by Chocohead** [comment]
Are names like `font` and `height` not deobf'd enough for you? :P

**Comment by modmuss50** [comment]
oh yeah, will look into it.

**Comment by modmuss50** [comment]
fixed, not sure how I missed those.

**Comment by Chocohead** [comment]
Also note that the naming in `ContainerScreen` conflicts with `Screen#width` and `#height`

**Comment by modmuss50** [comment]
nice spot, I hope there isnt any other instance of this happening.

**Comment by Chocohead** [comment]
Summarising into a more easy format to find renames in:
<details> 
  <summary>Method renames</summary>

   `net/minecraft/client/gui/menu/RealmsScreen#getButtons()Ljava/util/List; => buttons()Ljava/util/List;`
   `net/minecraft/client/gui/menu/RealmsScreen#getFontHeight()I => fontLineHeight()I`
   `net/minecraft/client/gui/menu/RealmsScreen#addButton(Lnet/minecraft/realms/AbstractRealmsButton;)V => buttonsAdd(Lnet/minecraft/realms/AbstractRealmsButton;)V`
   `net/minecraft/client/gui/menu/RealmsScreen#getRealmsScreen()Lnet/minecraft/realms/RealmsScreen; => getScreen()Lnet/minecraft/realms/RealmsScreen;`
   `net/minecraft/client/gui/menu/RealmsScreen#clearListeners()V => childrenClear()V`
   `net/minecraft/client/gui/menu/RealmsScreen#clearWidgets()V => buttonsClear()V`
   `net/minecraft/client/gui/menu/RealmsScreen#containsWidget(Lnet/minecraft/realms/RealmsGuiEventListener;)Z => hasWidget(Lnet/minecraft/realms/RealmsGuiEventListener;)Z`
   `net/minecraft/client/gui/menu/RealmsScreen#getStringWidth(Ljava/lang/String;)I => fontWidth(Ljava/lang/String;)I`
   `net/minecraft/client/gui/menu/RealmsScreen#wrapStringToList(Ljava/lang/String;I)Ljava/util/List; => fontSplit(Ljava/lang/String;I)Ljava/util/List;`

   `net/minecraft/client/gui/widget/SliderWidget#updateText()V => updateMessage()V`
   `net/minecraft/client/gui/widget/SliderWidget#onProgressChanged()V => applyValue()V`

   `net/minecraft/client/gui/widget/ButtonWidget#onPressed()V => onPress()V`

   `net/minecraft/client/gui/widget/AbstractListWidget#getEntryWidth()I => getRowWidth()I`
   `net/minecraft/client/gui/widget/AbstractListWidget#getEntryHeight()I => getItemHeight()I`
   `net/minecraft/client/gui/widget/AbstractListWidget#drawBackground()V => renderBackground()V`
   `net/minecraft/client/gui/widget/AbstractListWidget#getMaxScrollY()I => getMaxScroll()I`
   `net/minecraft/client/gui/widget/AbstractListWidget#getSelectedEntry(DD)I => getItemAtPosition(DD)I`
   `net/minecraft/client/gui/widget/AbstractListWidget#clampScrollY()V => capYPosition()V`
   `net/minecraft/client/gui/widget/AbstractListWidget#getScrollY()I => getScroll()I`
   `net/minecraft/client/gui/widget/AbstractListWidget#setX(I)V => setLeftPos(I)V`
   `net/minecraft/client/gui/widget/AbstractListWidget#getMaxScrollPosition()I => getMaxPosition()I`
   `net/minecraft/client/gui/widget/AbstractListWidget#getEntryCount()I => getItemCount()I`
   `net/minecraft/client/gui/widget/AbstractListWidget#renderCoverBackground(IIII)V => renderHoleBackground(IIII)V`

   `net/minecraft/client/gui/MultiInputListener#isActive()Z => isDragging()Z`
   `net/minecraft/client/gui/MultiInputListener#getInputListeners()Ljava/util/List; => children()Ljava/util/List;`

   `net/minecraft/client/gui/Screen#close()V => onClose()V`
   `net/minecraft/client/gui/Screen#onInitialized()V => init()V`
   `net/minecraft/client/gui/Screen#isAltPressed()Z => hasAltDown()Z`
   `net/minecraft/client/gui/Screen#onClosed()V => removed()V`
   `net/minecraft/client/gui/Screen#update()V => tick()V`
   `net/minecraft/client/gui/Screen#openUri(Ljava/net/URI;)V => openLink(Ljava/net/URI;)V`
   `net/minecraft/client/gui/Screen#doesEscapeKeyClose()Z => shouldCloseOnEsc()Z`
   `net/minecraft/client/gui/Screen#isShiftPressed()Z => hasShiftDown()Z`
   `net/minecraft/client/gui/Screen#drawBackground()V => renderBackground()V`
   `net/minecraft/client/gui/Screen#getStackTooltip(Lbaz;)Ljava/util/List; => getTooltipFromItem(Lbaz;)Ljava/util/List;`
   `net/minecraft/client/gui/Screen#isControlPressed()Z => hasControlDown()Z`
   `net/minecraft/client/gui/Screen#handleTextComponentClick(Ljm;)Z => handleComponentClicked(Ljm;)Z`

   `net/minecraft/client/gui/widget/ClickableScrolledSelectionList#width()I => getWidth()I`

   `net/minecraft/client/gui/menu/RealmsButton#getRealmsProxy()Lnet/minecraft/realms/AbstractRealmsButton; => getButton()Lnet/minecraft/realms/AbstractRealmsButton;`
   `net/minecraft/client/gui/menu/RealmsButton#isEnabled()Z => active()Z`
   `net/minecraft/client/gui/widget/RealmsButtonWidget#getTexId(Z)I => getSuperYImage(Z)I`
   `net/minecraft/client/gui/widget/RealmsButtonWidget#getY()I => getHeight()I`
</details>

<details> 
  <summary>Field renames</summary>

   `net/minecraft/realms/RealmsScreenProxy#realmsScreen => screen`
   `net/minecraft/realms/RealmsScreenProxy#LOGGER_REALMS => LOGGER`

   `net/minecraft/client/gui/DrawableHelper#ICONS => GUI_ICONS_LOCATION`
   `net/minecraft/client/gui/DrawableHelper#OPTIONS_BG => BACKGROUND_LOCATION`
   `net/minecraft/client/gui/DrawableHelper#STAT_ICONS => STATS_ICON_LOCATION`
   `net/minecraft/client/gui/DrawableHelper#zOffset => blitOffset`

   `net/minecraft/client/gui/widget/SliderWidget#progress => value`
   `net/minecraft/client/gui/widget/SliderWidget#gameOptions => options`

   `net/minecraft/client/gui/widget/AbstractListWidget#client => minecraft`
   `net/minecraft/client/gui/widget/AbstractListWidget#entryHeight => itemHeight`

   `net/minecraft/client/gui/ScreenComponent#active => isDragging`

   `net/minecraft/client/gui/Screen#listeners => children`
   `net/minecraft/client/gui/Screen#screenWidth => width`
   `net/minecraft/client/gui/Screen#client => minecraft`
   `net/minecraft/client/gui/Screen#fontRenderer => font`
   `net/minecraft/client/gui/Screen#screenHeight => height`
   `net/minecraft/client/gui/Screen#PROTOCOLS => ALLOWED_PROTOCOLS`
   `net/minecraft/client/gui/Screen#labelWidgets => labels`
   `net/minecraft/client/gui/Screen#uri => clickedLink`

   `net/minecraft/realms/RealmsButtonProxy#realmsButton => button`
</details>
This is all the methods I've found that are mismatched, might be worth checking all these are actually covered by the PR.

**Comment by modmuss50** [comment]
Does anyone have any further issues with this? If not I will most likely end up merging it.

**Pull request merged**
