### PR TITLE
Restore GUI names from 20w09a

### PR DESCRIPTION
**Pull request by Juuxel**
This PR restores many names that were removed in the 20w10a when they became obfuscated.

### CODE REVIEW

**Review by liach — APPROVED** [review]
Good fixup. Mojang names are ugly, and we need a quick cleanup pr (separate I suggest) after.

**Comment by modmuss50** [comment]
Yes, I think using most of the old names is ok for now, will make tools like migrate mappings useful if names do change later.

**Review by modmuss50 — APPROVED** [review]

**Review by CDAGaming — APPROVED** [review]
Yes please!

**Review by jaskarth — APPROVED** [review]
thank u for your service kind juuz

**Pull request merged**
