### PR TITLE
getDropTableID -> getLootTableId

### PR DESCRIPTION
**Pull request by Prospector**
This must've made it through in the AbstractBlock changes

### CODE REVIEW

**Comment by liach** [comment]
Should this be renamed to `loot table` than `drop table`?

**Comment by Prospector** [comment]
I do agree with you there, though really this was just the single bugfix

**Comment by liach** [comment]
A bug is still a refactor
Also I suggest just calling it "loot table". `drop table` is really a legacy name https://github.com/FabricMC/yarn/commit/6d3075daebae22e7938460743ba82a5f6618e329#diff-0fc22c45ea8a7363223df24d31b7f7caR202 and no longer applies because we call this type of things loot tables now (before it's loot supplier)

**Comment by Prospector** [comment]
Okay, updated. I hope this doesn't turn into another massive bikeshedding. Just wanted to get a simple bugfix in :P

**Review by liach — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Comment by Juuxel** [comment]
Hm, maybe `AbstractBlock.Settings.dropTableId` should also be changed.

**Review by Earthcomputer — APPROVED** [review]

**Pull request merged**
