### PR TITLE
Explain how to use an IDE in README.md

### PR DESCRIPTION
**Pull request by Lytigas**
masa explained this to me in the scicraft discord after he found out I was using enigma directly. I didn't know better because there wasn't documentation, so I figured I'd document what little I know.

### CODE REVIEW

**Comment by modmuss50** [comment]
wat? this repo doesnt have genSources? there is no reason to use an ide on this repo?

**Review by NeunEinser — COMMENTED** [review]
Yarn is only about providing mappings, which enigma is intended to be used for.

If you want to only look at decompiled code, yarn might simply not be the right place for that. This doku does not belong into yarn though, more in a general info page about fabric.

**Review by liach — CHANGES_REQUESTED** [review]
Seriously, look at #695. That pr already includes how you gets a deobfuscated minecraft combined jar `mapNamedJar` which will give deobfuscated source after piping through a decompiler.

The fabric-loom usage of yarn is not related to yarn itself and should not be present!

**Comment by liach** [comment]
I think I will add to my readme change in #695 that for vanilla research purposes, `mapNamedJar` is the most feasible; for modding purposes, fabric-loom will remap the jar for you.

**Comment by Lytigas** [comment]
Clearly I don't have a full grasp of the way these components interact yet; sorry to bother. If there's a guide and/or documentation I missed, I'd love to see it; otherwise I hope it can be worked on soon.

**Pull request closed without merging**
