### PR TITLE
add getSkyColor mapping to ClientWorld

### PR DESCRIPTION
**Pull request by Nolij**

### CODE REVIEW

**Review by enbrain — APPROVED** [review]
For your information, that method is mapped in 1.18.

https://github.com/FabricMC/yarn/blob/e0c26300f8475f16f54856125f5a98bc0d41ab71/mappings/net/minecraft/client/world/ClientWorld.mapping#L51-L53

**Review by liach — APPROVED** [review]

**Review by Shnupbups — APPROVED** [review]
Might be worth backporting a bunch of mappings from 1.18 to 1.17?

**Comment by liach** [comment]
@modmuss50 fyi this is a backport. might need a backport tag in the future

**Comment by modmuss50** [comment]
Oh, shit my bad, I broke it.

**Pull request merged**
