### PR TITLE
Standardize EntityData naming

### PR DESCRIPTION
**Pull request by Pyrofab**
A few implementations of `EntityData` had naming collisions, like `LivingEntity.EntityData` or `HorseEntity.EntityData`.
Other names seemed not descriptive enough, like `ZombieEntity.Data`.
I went for the naming scheme used by `FoxEntity.FoxData`, prefixing every implementation with the entity name.

### CODE REVIEW

**Review by LambdAurora — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Comment by liach** [comment]
just Data should be fine for preventing qualified name usage

**Comment by Pyrofab** [comment]
But Data is not explicit enough when used from within the class.

**Comment by liach** [comment]
or rename it to SpawmParameter as that's its primary usage.

**Comment by liach** [comment]
InitParameter, i mean.

**Comment by Pyrofab** [comment]
So you are suggesting to rename the base interface ? What naming scheme should the implementations use then ?

**Comment by liach** [comment]
The base should probably be like `EntityInitParameter` and the subclasses be `InitParameter` (given this class is used in `Entity#init` method)

**Comment by Pyrofab** [comment]
Honestly, InitParameter sounds like the most vague thing. Naming things based on where they are passed as parameters is a bit counterintuitive.

**Comment by Juuxel** [comment]
Could you update this to 20w07a?

**Review by modmuss50 — APPROVED** [review]

**Comment by liach** [comment]
After consideration, though the name `Data` may be inaccurate, we can change it in another pr later. Should've approved this one. Thanks pyrofab!

**Comment by Pyrofab** [comment]
That was indeed my thought, an `EntityData` rename requires more discussion.

**Pull request merged**
