### PR TITLE
Carver mappings

### PR DESCRIPTION
**Pull request by Stuff-Stuffs**

### CODE REVIEW

**Review by liach — APPROVED** [review]
Though it'd be better if you map other parameters, this is all right.

**Comment by Stuff-Stuffs** [comment]
Working on more Carver mappings right now

**Comment by Stuff-Stuffs** [comment]
This is my first time doing de-obfuscation, so it might not be up to snuff.

**Review by jaskarth — APPROVED** [review]

**Review by liach — APPROVED** [review]
looks good!

**Review by Juuxel — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Thanks a lot for this.

**Pull request merged**
