### PR TITLE
minor input mappings

### PR DESCRIPTION
**Pull request by kashike**

### CODE REVIEW

**Comment by asiekierka** [comment]
Input or PlayerInput?

**Comment by kashike** [comment]
It isn't really *from* a "player", it's just the current input being provided by something on the client.

**Comment by asiekierka** [comment]
LGTM

**Comment by SquidDev** [comment]
There's a bit of me which would wonder if `Input.update` is more accurate in this case? It recalculates the entire state, rather than progressing it based on a previous one.

Dunno if it's also worth mapping the other fields/methods in `Input` too?

**Comment by kashike** [comment]
Except it does use old state in `KeyboardInput` - it modifies fields.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
