### PR TITLE
More Social Interactions

### PR DESCRIPTION
**Pull request by OroArmor**
This also includes 
https://github.com/FabricMC/yarn/pull/1809
and 
https://github.com/FabricMC/yarn/pull/1808.

This adds some more mappings to the GUI of things, and could still use some improvement.

### CODE REVIEW

**Comment by ramidzkh** [comment]
concen

**Comment by OroArmor** [comment]
yes @ramidzkh ?

**Comment by enbrain** [comment]
Why did you make it include ongoing other pull requests? Generally, larger diff makes it harder to review.

**Comment by OroArmor** [comment]
Yeah, i did it for two reasons.

1. It helps me know what's going on with out discovering it out myself

2. I was hoping that they would be merged sooner to that the diff wouldn't be as large.

You could look at just the latest commit for all the changes

**Pull request closed without merging**
