### PR TITLE
Fixes for #895 & #1014

### PR DESCRIPTION
**Pull request by YanisBft**
#1014 was discussed a bit on discord, and we agreed that all packages should be singular

### CODE REVIEW

**Comment by liach** [comment]
Mind turn `fixes` into `fix` and `schemas` into `schema` instead for subpackages?

**Comment by i509VCB** [comment]
Have we thought of possibly making a subcategory within the data package so it would be `net.minecraft.data.fixer.NbtOps` for example.

**Review by liach — APPROVED** [review]
image
Looks great in enigma.

**Comment by Juuxel** [comment]
Note that this isn't a full fix for #895 as it also relates to the relevant method/field names in `Entity`.

i509VCB: Datafixer stuff should not be moved to `net.minecraft.data` as that package only has data generation tools.

**Review by Juuxel — APPROVED** [review]

**Comment by YanisBft** [comment]
@Juuxel, as I said on your issue, entity nbt is still named "Portal" and does not contain "NetherPortal", that's why I was not sure to rename these fields

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
