### PR TITLE
1.19.1-rc1 stuff

### PR DESCRIPTION
**Pull request by apple502j**
RunningTaskScreen renamed due to Mojang refactor on usage.

### CODE REVIEW

**Review by liach — APPROVED** [review]
Looks good on web

**Comment by modmuss50** [comment]
Many merge conflicts :)

**Comment by apple502j** [comment]
@modmuss50 Actually this PR can just be closed, since #3227 is based on this PR and thus contains all changes from this :P

**Comment by modmuss50** [comment]
Ah nice, that makes things easier. Thanks 👍

**Pull request closed without merging**
