### PR TITLE
Update World.mapping

### PR DESCRIPTION
**Pull request by enbrain**
* `method_24794` → `isInBuildLimit `
* `method_25952` → `isInvalidVertically`
* `method_25953` → `isValid`
* `isHeightInvalid` → `isOutOfBuildLimitVertically`
* `isValid` → `isValidHorizontally`

### CODE REVIEW

**Review by Runemoro — CHANGES_REQUESTED** [review]
Rather than having different names for everything, why not have them all follow the pattern `is(Valid/Invalid)(Vertically/Horizontally/)`? So we'd have:
 - `isValid` `isInvalid`
 - `isValidHorizontally` `isInvalidHorizontally`
 - `isValidVertically` `isInvalidVertically`

**Comment by liach** [comment]
hmm what, height is vertical

**Comment by enbrain** [comment]
Oops...

**Review by Gegy — APPROVED** [review]

**Review by liach — APPROVED** [review]

**Comment by enbrain** [comment]
This PR was originally targetting 1.16.2, but it's still relevant in 1.16.3.

**Comment by i509VCB** [comment]
Isn't literally every PR for 1.16.2 still relevant to .3 lol

**Review by jaskarth — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
