### PR TITLE
Use "offhand" instead of "offHand"

### LINKED ISSUE #2818: LivingEntity.getOffHandStack -> getOffhandStack, PlayerInventory.offHand -> offhand
To match the capitalisation used elsewhere in Yarn and Minecraft (the game uses "offhand" in localised strings).

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #2818

Question: should we remap `Hand.OFF_HAND` (an enum)?

### CODE REVIEW

**Review by liach — APPROVED** [review]

**Comment by Juuxel** [comment]
> Question: should we remap Hand.OFF_HAND (an enum)?

No, because they have the internal name field that should match the field name. I think that's just Mojang being inconsistent: at least we can be consistent and choose the most common spelling.

**Review by Juuxel — APPROVED** [review]

**Review by enbrain — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Comment by modmuss50** [comment]
Uhh, my bad for merging this refactor. I dont think it should have been merged this late into a dev cycle....

net.minecraft.util.Hand is also still wrong.

**Comment by modmuss50** [comment]
Ah, just seen the comment above. Im not a big fan of this.

**Comment by Juuxel** [comment]
> net.minecraft.util.Hand is also still wrong.

That's an enum so it can't really be renamed (`name()` would return the wrong value).

**Pull request merged**
