### PR TITLE
Updates ChestEntityModel Mapping

### PR DESCRIPTION
**Pull request by ghost**
Code from class for assisting in review, simply renames `method_2799` to `render` and `method_2798` to `getLid`:

For code see ChestEntityModel class.

### CODE REVIEW

**Comment by ghost** [comment]
I can do a similar PR to 1.14.4 branch if that helps.

**Comment by modmuss50** [comment]
Don’t worry about that, I’ll merge it back with the others at some point

**Review by modmuss50 — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Comment by ghost** [comment]
Did you also forget to merge this PR aswell modmuss? Just wondering.

**Comment by modmuss50** [comment]
No, as it only had 1 review when I reviewed it.

**Pull request merged**
