### PR TITLE
Try to migrate to mapping io

### PR DESCRIPTION
**Pull request by liach**
Still needs stitch for jar merger and rewrite intermediary after #2708

The product mapping file is smaller due to mapping io skipping over meaningless mappings (e.g. ignore wholesale when named, intermediary, official are all same, skipping named when it does not differ from intermediary)

removed a few useless tasks and antique import/export mappings for official -> intermediary migration for yarn

### CODE REVIEW

**Comment by liach** [comment]
@modmuss50 In case you are interested, this is a diff between the old and new tiny v1 outputs: https://gist.github.com/5c15be78d81efd0c79ba8843fe65edcc it omits the entry if 3 names are the same and omits the named column if it's same as intermediary

**Comment by liach** [comment]
Drafting as I will base this on #2708; waiting for it to get merged first.

**Comment by liach** [comment]
Current diff for v1 after sorting: https://gist.github.com/liach/50efe22a6aa24bf0087bca77f2b6df32

For v2, sorting is more complex. In addition, sorting probably should be done in mapping io; see https://github.com/FabricMC/mapping-io/issues/9

**Comment by Juuxel** [comment]
> The product mapping file is smaller due to mapping io skipping over meaningless mappings (e.g. ignore wholesale when named, intermediary, official are all same, skipping named when it does not differ from intermediary)

I wonder if that makes it do the same as loom: FabricMC/fabric-loom#506

**Comment by liach** [comment]
Fyi I will put this on hold given mapping-io's lack of ability to sort the mapping tree. The lack of auto name propagation to other namespaces is a minor issue too.

**Comment by modmuss50** [comment]
Sorting isnt a big issue IMO, other than beign easier to diff the output, its not a major issue.

**Comment by liach** [comment]
Busy recently (so am not reviewing and submitting or even fixing my own prs). Will take some time to work on a better diff generator beyond text editor java programs once I am free.

**Comment by NebelNidas** [comment]
Can be closed now, right?

**Comment by modmuss50** [comment]
Yes, I the next thing to do will be to remove the old code and also fix the perf regression when saving (something I started looked at)

**Comment by liach** [comment]
Thanks for reminding me to close outdated pull requests :+1:

**Pull request closed without merging**
