### PR TITLE
Bring back BER.render()

### PR DESCRIPTION
**Pull request by falseresync**

### CODE REVIEW

**Comment by natanfudge** [comment]
Why did it get removed in the first place? Did the intermediary name change?

**Comment by falseresync** [comment]
Idk, that is not the first time such thing happens. Some say it is because obfuscation changes

**Comment by natanfudge** [comment]
It seems like it wasn't matched correctly @modmuss50 ?

**Comment by liach** [comment]
A new parameter was added.

**Review by liach — APPROVED** [review]

**Comment by natanfudge** [comment]
In [19w41](https://github.com/FabricMC/yarn/commit/841e352c6199acbc64723771a83db17ecef9d76d#diff-7a0bfb2b15765cf08f254b5066fcb2ef) it got another parameter, but the name stayed, in [19w42 ](https://github.com/FabricMC/yarn/commit/6fa1e34c83e3aa42af7e80efad710b9072671e72#diff-7a0bfb2b15765cf08f254b5066fcb2efL4) the name got removed for seemingly no reason?

**Comment by modmuss50** [comment]
It didn’t show up in matcher for me to match. Not sure why.

**Comment by liach** [comment]
hmm i guess that was a rebasing issue from me

**Pull request merged**
