### PR TITLE
Fix visibility errors

### LINKED ISSUE #615: [URGENT - BEFORE 1.14 STABLE] Fix visibility errors
```
Reading JAR...
Reading mappings...
ERROR: Must be in one package: net/minecraft/client/gui/widget/LevelListWidget$LevelItem and net/minecraft/client/gui/menu/LevelSelectScreen (field searchBox)
ERROR: Must be in one package: net/minecraft/client/gui/widget/MultiplayerServerListWidget and net/minecraft/client/gui/menu/MultiplayerScreen (method b)
ERROR: Must be in one package: net/minecraft/client/gui/widget/MultiplayerServerListWidget$ServerItem and net/minecraft/client/gui/menu/MultiplayerScreen (field serverListWidget)
ERROR: Must be in one package: net/minecraft/item/block/BlockItem and net/minecraft/item/ItemUsageContext (field hand, field world, field player)
ERROR: Must be in one package: net/minecraft/server/PlayerManager and net/minecraft/server/config/ServerConfigList (method contains)
ERROR: Must be in one package: net/minecraft/structure/generator/EndCityGenerator and net/minecraft/structure/SimpleStructurePiece (field structure, field placementData, field pos)
ERROR: Must be in one package: net/minecraft/structure/generator/EndCityGenerator and net/minecraft/structure/StructurePiece (field o)
ERROR: Must be in one package: net/minecraft/structure/generator/EndCityGenerator$1 and net/minecraft/structure/SimpleStructurePiece (field placementData)
ERROR: Must be in one package: net/minecraft/structure/generator/EndCityGenerator$2 and net/minecraft/structure/SimpleStructurePiece (field placementData)
ERROR: Must be in one package: net/minecraft/structure/generator/EndCityGenerator$3 and net/minecraft/structure/SimpleStructurePiece (field placementData)
ERROR: Must be in one package: net/minecraft/structure/generator/EndCityGenerator$3 and net/minecraft/structure/StructurePiece (field o)
ERROR: Must be in one package: net/minecraft/structure/generator/EndCityGenerator$4 and net/minecraft/structure/SimpleStructurePiece (field placementData)
ERROR: Must be in one package: net/minecraft/world/chunk/UpgradeData and net/minecraft/util/palette/PalettedContainer (method get)
ERROR: Must be in one package: net/minecraft/world/gen/feature/StructureFeatures and net/minecraft/structure/StructureStart (field children)
```

### PR DESCRIPTION
**Pull request by Runemoro**
- `net.minecraft.util.palette` -> `net.minecraft.world.chunk` (used by `UpgradeData`)
 - `net.minecraft.world.structure.generator` -> `net.minecraft.structure` (uses `StructurePiece`)
 - `net.minecraft.world.gen.feature.StructureFeatures` -> `net.minecraft.structure` (uses `StructurePiece`)
 - `net.minecraft.item.block` -> `net.minecraft.item` (uses `ItemUsageContext`)

### CODE REVIEW

**Comment by modmuss50** [comment]
Seems fine by me, after this is pulled in, I can hook yarn up to run the checker tool on build, and then using a CI to check PRs might not be a bad idea.

**Comment by asiekierka** [comment]
Just remember: Don't block PRs or builds over it on snapshot releases. On stable, absolutely; on snapshots, no.

**Comment by NeunEinser** [comment]
Why wouldn't you enforce it on snapshots right away?

**Comment by asiekierka** [comment]
The churn is fast. Having a meaningful mapping out to modders is more important than a 100% correct mapping, in that case.

**Review by asiekierka — APPROVED** [review]

**Pull request merged**
