### PR TITLE
Lots of loot table work

### PR DESCRIPTION
**Pull request by SquidDev**
I just wanted to drop items, and then ended up a lot further down the rabbit hole than I meant to.

### CODE REVIEW

**Comment by liach** [comment]
I suggest you wait a bit on this. In loot tables there are complex inheritance that some classes inherit a method from both superclasses and interfaces with the same name, which enigma currently fails to handle.

**Comment by asiekierka** [comment]
"wait a bit on this"

First of all, a quick run of tiny-remapper should detect naming conflicts, if any exist. Just run "gradle build" and use the resulting .tiny.gz to map a merged JAR from "official" to "named".

Second, we can't really wait.

**Comment by liach** [comment]
Well, I was not aware of the tiny-remapper. Now I am.

**Comment by asiekierka** [comment]
It's fine.

Our plan in the longer term is to add automatic tests to the buildscript which do exactly that.

**Comment by SquidDev** [comment]
liach was right in there being conflicts. I've manually patched it, but don't know if this is OK, or if it'd be better to remove that mapping for now. tiny-remapper is no longer complaining, but I don't know if there are any other verification steps I can take.

**Comment by asiekierka** [comment]
This is the best step. There's also findMappingErrors in Weave which finds class visibility issues - I need to go through *that* at some point as to ditch the PublicAccessTransformer hack.

**Pull request merged**
