### PR TITLE
21w37a

### PR DESCRIPTION
**Pull request by Player3324**

### CODE REVIEW

**Comment by liach** [comment]
On a side note, make sure you run `generatePackageInfoMappings` every time you update yarn to a new minecraft version

**Comment by modmuss50** [comment]
Also make sure to push this to a new branch, dont merge this PR into the 1.17.1 branch.

**Comment by liach** [comment]
On a side note, I propose to just cherry pick yarn commits from the exp snapshots onto 21w37a later manually. They probably cherry pick their work from experiments to regular snapshots as well.

**Comment by mschae23** [comment]
> On a side note, I propose to just cherry pick yarn commits from the exp snapshots onto 21w37a later manually. They probably cherry pick their work from experiments to regular snapshots as well.

I can port my contributions from the experimental snapshots to 21w37a once that works, at least.

**Comment by modmuss50** [comment]
Pushed stright to the new branch. 👍

**Pull request closed without merging**
