### PR TITLE
Some network stuff, and minor atomic stack/affine transformation revisit

### PR DESCRIPTION
**Pull request by liach**
Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Review by Juuxel — APPROVED** [review]

**Review by YanisBft — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Good to merge once conflict fixed.

**Comment by liach** [comment]
Found another field that can be mapped. ALso I think I should try unpicking

**Comment by liach** [comment]
Turns out unpick is weird. In my first run of `yarnU`, it unpicks the constant for max text length; in the second run, it unpicks the constant for the max var long size, but not that for the max var int size. I don't know how unpick works, but apparently it is working in an inconsistent and unreliable way. So much it... We are good with javadocs and `{@value}` links I guess

**Comment by liach** [comment]
Hmm, so yeah, I shouldn't have used unpick. Those constants except the string and text length ones are private.

So is the goal of unpick to make constants exposed in public APIs more understandable? And it doesn't worry too much about impl detail constants, I assume?

**Pull request merged**
