### PR TITLE
Fix the update base script calling a non-existent contains function

### PR DESCRIPTION
**Pull request by haykam821**

### CODE REVIEW

**Review by YanisBft — APPROVED** [review]
Thank you, I don't know why I saw "contains" in the docs

**Comment by haykam821** [comment]
Hopefully the script can be hardened to comment an error message with stack trace and remove the label as well. This should be good for now to fix #2484.

**Review by liach — APPROVED** [review]
:smile:

**Comment by modmuss50** [comment]
Really need to split this out into a proper custom action with some tests as its a right pita to test atm

**Pull request merged**
