### PR TITLE
Tag -> Nbt

### PR DESCRIPTION
**Pull request by ChloeDawn**
- Remapped Tag -> Nbt class names
- Remapped existing mappings for references to the classes
- ~~Migrated toTag/fromTag -> serialize/deserialize~~*

*Will be reverted tomorrow when I have the time (toNbt/fromNbt)

### CODE REVIEW

**Comment by Prospector** [comment]
We're going back to serialize and deserialize? I'm not against it but I can't remember why we changed it to toTag/fromTag in the first place...it must've been a good reason?

**Comment by RedstoneParadox** [comment]
It was probably changed to avoid similarities to MCP.

**Comment by liach** [comment]
NBT is named binary tag. Now we use `Tag` which is already accurate enough.

**Comment by LemmaEOF** [comment]
@liach it's accurate, but it clashes with the `Tag` system that replaces oredicts.

**Comment by LemmaEOF** [comment]
@Prospector @RedstoneParadox We've talked things over in the discord, and `serialize/deserialize` is gonna be changed back in the morning, Kitten's time. In future, we're going to stick with `to<DataStorageType>` and `from<DataStorageType>`, as noted in the [draft of CONTRIBUTING.md](https://github.com/FabricMC/yarn/pull/477).

**Comment by ChloeDawn** [comment]
The ticket description has been updated accordingly

**Comment by liach** [comment]
:+1: for `toNbt`/`fromNbt`

**Comment by ChloeDawn** [comment]
Will reopen after the next snapshot has been processed

**Comment by Prospector** [comment]
Remade for 1.15.2 #1077

**Pull request closed without merging**
