### PR TITLE
Move loot package out of world

### PR DESCRIPTION
**Pull request by YanisBft**
All the datapack stuff (`advancement`, `recipe`, `tag`, `predicate` packages) is out of the `world` package, except `loot`
This PR fixes that

### CODE REVIEW

**Review by Juuxel — APPROVED** [review]

**Review by liach — APPROVED** [review]

**Review by modmuss50 — CHANGES_REQUESTED** [review]
This is not how you rename mappings. Each mapping file also has the yarn name on the first line.

Please please use engima or at least be very careful when touching the mappings outside of engima.

**Comment by liach** [comment]
hmm, we should have add enigma directory mapping verification for the gradle check task

**Comment by modmuss50** [comment]
Yes, this should have failed to build.

**Comment by YanisBft** [comment]
I was too lazy to move the files one by one, so I forgot half of the things >< Sorry!

**Review by liach — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
