### PR TITLE
Map WorldEventConstants

### PR DESCRIPTION
**Pull request by apple502j**
RIP unpick 21w11a-21w11a
All names copied from unpick mapping

### CODE REVIEW

**Review by liach — CHANGES_REQUESTED** [review]
Where are my javadocs and upgraded unpick notations

**Comment by YanisBft** [comment]
Do we agree on suffixing the constant classes with "Constants"? Because honestly WorldEvents would suffice

**Comment by apple502j** [comment]
Maybe `WorldEvents` works, but unsure if the package name is not confusing - unpick is under `net.fabricmc.yarn.constants`, but I did not introduce "constants" package yet, maybe should I?

**Comment by OroArmor** [comment]
Also shouldnt this pr fix the unpick file to use the new constant file rather than the old manual one?

**Comment by YanisBft** [comment]
idk if a new package is needed, imo constant classes should be put under the same package of their use (the use we guessed)

**Comment by liach** [comment]
If you find it confusing, `WorldEventIds` is an okay alternative

**Comment by apple502j** [comment]
Someone can redo it later with javadocs and unpick, i'm gonna close

**Pull request closed without merging**
