### PR TITLE
Fix name conflict with getPrimeSuspect

### LINKED ISSUE #3129: WardenAngerManager has two getPrimeSuspect
One returns nullable and one returns optional + LivingEntity check iirc.

### PR DESCRIPTION
**Pull request by apple502j**
Fixes #3129

Better names? The only difference from `getPrimeSuspect` is that the return type is `Optional<LivingEntity>` instead of `@Nullable Entity`.

### CODE REVIEW

**Comment by enbrain** [comment]
`public`/`private` is also the difference. Would it make sense to use `getPrimeSuspect`/`getPrimeSuspectInternal`?

**Comment by haykam821** [comment]
Does this method return an empty optional if the prime suspect is not a `LivingEntity`? I would name it `getLivingPrimeSuspect` with `@return` documentation for how the optional is empty when there is no suspect or a non-living suspect.

**Comment by apple502j** [comment]
I'll use the internal suffix, then.

@haykam821 I don't like "living" prefix because without context this means non-discarded entities - although as of 18a wardens should never get angry at discarded entities.

**Comment by haykam821** [comment]
The "living" prefix is not an issue for the class itself. I think there is enough of a distinction between entities that can live and non-discarded entities.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
