### PR TITLE
Moved all S2C/C2S packets

### LINKED ISSUE #622: Move packets out of `net.minecraft.server` and `net.minecraft.client`
Packets are shared on both sides (that's their purpose!), so they don't belong in the side-specific packages. They should all be moved into `net.minecraft.network.packet.s2c` and `net.minecraft.network.packet.c2s`.

### PR DESCRIPTION
**Pull request by YanisBft**
Fixes #622 . As Runemoro said, packets are not exclusive to either client or server side, so it makes no sense to let them in client or server packages. According to the thumbs up, many people seem to agree on it.

Additionally, some packets were renamed:
- `EntityPotionEffectS2CPacket` -> `EntityStatusEffectS2CPacket`, as it's the name used everywhere else for now. After this PR, #915 can be closed, as the other issues described there are already fixed
- `RemoveEntityEffectS2CPacket` -> `RemoveEntityStatusEffectS2CPacket`, to match the above
- `GuiActionConfirmC2SPacket` -> `ConfirmGuiActionC2SPacket`, to match the S2C one

### CODE REVIEW

**Comment by liach** [comment]
assuming we rarely do qualified reference (i.e. no import), i'd prefer clientbound/serverbound for package names

**Comment by liach** [comment]
Another way to group packets is probably by their recipients (the generic T in packet class). they are more specific than c2s/s2c packets (e.g. server play, client play, client login, server login, etc.)

**Comment by YanisBft** [comment]
> assuming we rarely do qualified reference (i.e. no import), i'd prefer clientbound/serverbound for package names

Hum, aren't they confusing names? I think there's nothing clearer than `s2c`/`c2s`. Waiting for more opinions about your idea tho.

> Another way to group packets is probably by their recipients (the generic T in packet class). they are more specific than c2s/s2c packets (e.g. server play, client play, client login, server login, etc.)

I think it won't be consistent with how we sort classes in other packages (ie we don't sort features by the feature config they use). Again, waiting for more opinions.

**Comment by Pyrofab** [comment]
`s2c` and `c2s` can be confusing for newcomers when they don't know what the abbreviations mean. Maybe keeping them in class names (for brevity) but using full English names in packages would help make things more intuitive.

**Comment by Player3324** [comment]
We already had this *bound discussion multiple times, It is just a bad ambiguous scheme and strictly inferior to c2s/s2c outside some minor stylistic concerns. 

I wouldn't mind a state sub-hierarchy, e.g. `n/m/network/packet/c2s/play/ConfirmGuiActionC2SPacket`, but probably nothing beyond that since direct vanilla packet use is a rather low level facility anyway.

**Comment by Prospector** [comment]
Again, though, it's not actually ambiguous since XBound and Xbound are entirely different in the english language. I don't think yarn should cater to an incorrect understanding of the english language, personally.

At some point one must learn what C2S and S2C means in the first place, and since Clientbound/Serverbound will be intuitive for most english natives and likely many non-natives, anyone who doesn't already know what it means can simply learn it as everyone must for C2S/S2C anyway. Once they have learned it, they will not just have learned a single convention that one project uses, but something valuable to know about the english language for any future encounters of the *bound suffix in the rest of their life.

**Comment by YanisBft** [comment]
Any more opinions on this? What should I do, rename s2c/c2s packages to clientbound/serverbound? Create sub-packages for each listener type?

**Comment by Pyrofab** [comment]
Probably create sub-packages for the listener types, although it's probably not immediately necessary.

**Comment by YanisBft** [comment]
Splitted into subpackages

**Review by liach — APPROVED** [review]
Looks good after a fetch locally.

**Comment by liach** [comment]
I hope this one gets decided soon so that I can work on renaming some fields in packet classes (related to networking api v1)

**Review by Player3324 — APPROVED** [review]
LGTM conceptually, didn't check details. Thanks for doing this!

**Comment by liach** [comment]
Just need a final round of reviews. Ready to merge imo after that.

**Review by Earthcomputer — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Pull request merged**
