### PR TITLE
Fix method name in VoronoiBiomeAccessType

### PR DESCRIPTION
**Pull request by Kroppeb**
Changes the `calcChance` to `calcSqrDistance` as the old name didn't make sense.

### CODE REVIEW

**Comment by YanisBft** [comment]
You mean `sqrt`?

**Comment by Kroppeb** [comment]
No `sqrt` would mean `sqrt(distance)` but `sqr` is `distance²` which is commonly used to compare multiple distances as it's much faster which is what this is used for.

**Comment by liach** [comment]
Just call it `calcuateSquaredDistance` I guess, this is not really chance

**Comment by Kroppeb** [comment]
Oh, I just assumed the standard was `sqr` as that's how the private function in the class is called. But I noticed that all other places use `squareDistance`. Should I rename `sqr` too then?

**Comment by liach** [comment]
Sure, both are private methods so renaming them has no mod impact. Also see #1062 (consider renaming distribute to show that this is assigning a point to the closest point out of the 4 near it)

**Comment by Kroppeb** [comment]
* Voronoi is quite a good name. Even though it's not exactly correct as it only checks the 8 surrounding biome sections, ignoring the fact that seeds of other sections further away could technically be closer. It still helps a lot with understanding what is going on.
* `distribute` gives a "random" value in the range `[-0.45, 0.45[`. I feel the name is descriptive enough.

**Review by YanisBft — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]
Looks good (though `sqr` is just as good as `square` IMO)

**Review by liach — APPROVED** [review]

**Review by Player3324 — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Comment by liach** [comment]
So can #1062 be considered fixed now?

**Pull request merged**
