### PR TITLE
Mapped all methods and fields in village package

### PR DESCRIPTION
**Pull request by liach**
Seems there is a broken method in resource listener or so. As a result, there is some removal diff, but it shouldn't break the merge.

### CODE REVIEW

**Comment by liach** [comment]
In fact, those removals are from useless diffs in #455.

**Review by asiekierka — APPROVED** [review]
depletes and consider sound a bit weird, but I trust you on those I guess

**Comment by liach** [comment]
Consider means ticking all and removing invalid ones. Depletes means to decrease the input stacks' size with the villager trade.

**Comment by asiekierka** [comment]
>Consider means ticking all and removing invalid ones.

Isn't that just "ticking"?

>Depletes means to decrease the input stacks' size with the villager trade.

Isn't that commitTrade or decrease or something? Not sure here, just ideas

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
