### PR TITLE
Remove mapYarnJar task

### PR DESCRIPTION
**Pull request by Runemoro**
It does the same thing as `mapNamedJar` except without parameter names.

### CODE REVIEW

**Comment by liach** [comment]
Hmm, when I added that task, I recall that task does not map stitch-inferred names.

**Comment by Runemoro** [comment]
@liach Which task are you talking about?

I can confirm that `mapNamedJar` does map enum names. If you're talking about `mapYarnJar`, I don't see why we need a jar that's missing stitch names?

**Comment by liach** [comment]
Yeah before I think I renamed old map named jar that does not include inferred names as this yarn jar for those that need such a jar. guess we can remove it

**Review by liach — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]
I see no use in it, will leave it a bit of time to make sure no one uses it for some reason.

**Review by YanisBft — APPROVED** [review]

**Comment by modmuss50** [comment]
No one has said anything yet, so it can go.

**Pull request merged**
