### PR TITLE
Fix the player parameter of methods used for playing sounds in the World class being unclear

### PR DESCRIPTION
**Pull request by haykam821**

### CODE REVIEW

**Review by liach — APPROVED** [review]
If we want to be clear, we can document that when the player is passed, the player's client already played the sound and notified the server, so we don't try to ask that player's client to play the sound again :smile:

**Comment by haykam821** [comment]
I think that this is good since the confusion is mostly from a server-only standpoint. When the same code is being ran on both the server and client, what you mentioned will come into effect.

**Comment by liach** [comment]
hmm, what is the main usages of this? in handling client input or when server does things automatically like by schedule?

**Comment by haykam821** [comment]
Vanilla uses these methods for playing sounds on both the client and server. On the client, the sound is played if `except` is the client's player. On the server, the sound is played to all nearby players except `except`. This causes the sound to be played to all players for an action that is called on both the server and client, like block interactions.

**Comment by liach** [comment]
then this should be like an actor/sender as it plays sound on client.

**Review by YanisBft — APPROVED** [review]

**Comment by liach** [comment]
If this parameter rename turns out unsuitable, we can always improve it without affecting mapping users later. So why not.

**Pull request merged**
