### PR TITLE
Minor refactor

### PR DESCRIPTION
**Pull request by Prospector**
should be a quick merge, just a few fixes

### CODE REVIEW

**Review by Ueaj-Kerman — APPROVED** [review]

**Review by TheGlitch76 — APPROVED** [review]
i have read all 10,887 lines and i am in love

**Review by modmuss50 — CHANGES_REQUESTED** [review]
I dont know if you joking or not

**Comment by modmuss50** [comment]
this is a joke.

**Review by liach — CHANGES_REQUESTED** [review]
@Prospector you targeted the wrong branch, target the april fools branch plz

**Pull request closed without merging**
