### PR TITLE
Finish ProfilerTimer mapping

### PR DESCRIPTION
**Pull request by RDIL**
This is my first mapping that I've ever written, so please let me know if I did something wrong.

Also, this exists on latest, so figured I would add it.

Thanks in advance 😃

### CODE REVIEW

**Comment by liach** [comment]
I wonder if we still add to 1.14.4 mappings 🤔

**Review by liach — APPROVED** [review]

**Comment by RDIL** [comment]
@liach modmuss said that if it targets latest it can be backported, and this change is on master but was never backported for some reason.

**Comment by liach** [comment]
@modmuss50 decide then

**Comment by modmuss50** [comment]
No reason why not, not sure why it failed to build.

**Comment by liach** [comment]
The build failure may be caused by what's fixed in #1260?

**Comment by RDIL** [comment]
I can cherry-pick that commit onto this branch if you want.

**Comment by RDIL** [comment]
@liach that fixed it!

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
