### PR TITLE
Rename OreBlock to ExperienceDroppingBlock

### LINKED ISSUE #3281: `OreBlock` is inaccurate
`OreBlock` is extended by a non-ore block `SculkBlock`. Shnupbups suggested `ExperienceDroppingBlock` in fabric discord.

> Shnupbups: yeah `OreBlock` is really just `ExperienceDroppingBlock` or something but that's not a nice name

https://discord.com/channels/507304429255393322/521545796882006027/990536847539191828

### PR DESCRIPTION
**Pull request by NoahvdAa**
Fixes #3281. I thought about other names but couldn't come up with anything better than this, so ExperienceDroppingBlock it is ^_^.

### CODE REVIEW

**Review by YanisBft — APPROVED** [review]
I'm fine with this rename, and I also think it's not that impactful?

**Review by enbrain — COMMENTED** [review]
References to `OreBlock` in javadoc need to be updated.

https://github.com/FabricMC/yarn/blob/51d6fad08d07e9614317cfbc28f1aa05f76a796f/mappings/net/minecraft/block/AbstractBlock.mapping#L662

https://github.com/FabricMC/yarn/blob/51d6fad08d07e9614317cfbc28f1aa05f76a796f/mappings/net/minecraft/block/AbstractBlock.mapping#L666

**Review by enbrain — APPROVED** [review]

**Comment by apple502j** [comment]
This is very impactful, can find 150+ references with package name, probably more if someone asterisk imports. I know this includes old versions but yes, it is impactful (threshold I use is 50)

**Review by apple502j — APPROVED** [review]
Maybe merge to 1.19.3?

**Review by modmuss50 — APPROVED** [review]
Yeah lets merge it. Otherwise we never will 👍

**Pull request merged**
