### PR TITLE
Rename grass to short grass

### PR DESCRIPTION
**Pull request by YanisBft**
And update enigma

### CODE REVIEW

**Review by Benonardo — APPROVED** [review]

**Comment by ErrorCraft** [comment]
`Blocks.GRASS` should also be renamed to `SHORT_GRASS`.

**Comment by haykam821** [comment]
Is `Blocks.SHORT_GRASS` not already the name? The name should come from the string used in the method call to register the block.

**Comment by YanisBft** [comment]
Yeah double-checked, the name is auto-generated

**Comment by ErrorCraft** [comment]
Ah, alright. Wouldn't the item names be auto-generated too then, or does it not generate `SHORT_GRASS` because it doesn't have a string in the method it calls where it can take the name from?

**Comment by YanisBft** [comment]
> Ah, alright. Wouldn't the item names be auto-generated too then, or does it not generate `SHORT_GRASS` because it doesn't have a string in the method it calls where it can take the name from?

Exactly, names of block items are not generated because there's no string in the register method

**Comment by haykam821** [comment]
The item fields are initialized like `Items.register(SHORT_GRASS)`, so there isn't a string to derive a name from. However, FabricMC/name-proposal#9 expands the field naming system to support additional name providers, and naming fields transitively is a possibility.

**Review by Shnupbups — APPROVED** [review]

**Comment by Shnupbups** [comment]
Requires developer review for changing gradle properties

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
