### PR TITLE
Rename several methods to be suffixed

### PR DESCRIPTION
**Pull request by SquidDev**
- `*TagList` -> `*ListTag`
 - `*TagCompound` -> `*CompoundTag`
 - Several mappings within the `ServerCommandSource`.

Some things to discuss:

 - Do we need `Tag` on methods within the `TagList` classes?
 - Do we need `Server` on methods within `ServerCommandSource`?

### CODE REVIEW

**Comment by Prospector** [comment]
I'd say no to both questions

**Comment by Prospector** [comment]
Wait... I change my mind. Yes to `Do we need Tag on methods within the TagList classes?` and no to `Do we need Server on methods within ServerCommandSource?`

**Comment by asiekierka** [comment]
No to both. nbt.ListTag is already in the "NBT" context, so we can assume future entries being "NBT"-context is implied.

**Comment by Prospector** [comment]
IMO having nbt.getInt and the others right alongside nbt.getList could be a little confusing, that's why I said it should have the tag suffix

**Comment by asiekierka** [comment]
I sort-of disagree, but I'll get more opinions in.

**Pull request merged**
