### PR TITLE
backport "add weather and time mappings (#1570)" to 1.16.1

### PR DESCRIPTION
**Pull request by fiws**
I just cherry-picked my merged commit. Should also work fine for 1.16.1

### CODE REVIEW

**Review by YanisBft — APPROVED** [review]

**Comment by YanisBft** [comment]
Marking as ready to merge as these mappings were already approved

**Review by liach — CHANGES_REQUESTED** [review]
Needs verification since world hierarchy including methods that handle time of the day has been changed in 27a.

**Comment by liach** [comment]
Hope it works fine.

**Comment by modmuss50** [comment]
Oh right, I should have checked that...

**Pull request merged**
