### PR TITLE
Fix swapped names

### PR DESCRIPTION
**Pull request by enbrain**

### CODE REVIEW

**Review by YanisBft — APPROVED** [review]

**Review by liach — APPROVED** [review]
matcher i guess

**Comment by Player3324** [comment]
Did anyone check how/when this happened? Especially the field name shouldn't get mixed up in the matching process.

**Comment by liach** [comment]
For the world border center one, it is just that shnupbups messed it up (the getters are written not in the expected x first z second order! weird indeed!) now checking the language definition one.

**Comment by liach** [comment]
For the language definition one, it appears to have been between 21w08b and 21w10a. The fields and parameters seemed to have swapped order? Or did mojang rename the deobfed methods?

**Comment by Player3324** [comment]
Need to see if it happens again, may have been a manual mismatch.

**Comment by liach** [comment]
For that language definition one, I'd really say matcher is doing a good job. From a glimpse, all things matched are the same; the only change is the names of the deobfuscated methods (like the first method still return first field, 2nd method still return 2nd field, param order stayed, but the two methods swapped names). Need to dig into that more; maybe we just assumed the deobf'd names are right when we matched initially, and matcher simply carries on our assumptions?

**Comment by Player3324** [comment]
https://github.com/sfPlayer1/Matcher/commit/1c6b8cbbd21b4409235a697fbc276847ceef8294 may have improved things either way, I'd wait for another clear instance before spending too much time investigating

**Pull request merged**
