### PR TITLE
Add unnecessary Eclipse files to .gitignore

### PR DESCRIPTION
**Pull request by haykam821**

### CODE REVIEW

**Review by liach — APPROVED** [review]
Dunno why you run eclipse here but sure

**Comment by modmuss50** [comment]
Should really be using a git include solves issues like this as someone is bound to come along with something else to ignore.

**Comment by haykam821** [comment]
I have no idea where I got these files, but I accidentally committed them in 9aecefec711f879199fa0a37e374a5ae6ff04f43. They might as well be included if IntelliJ IDEA gets its own section.

**Comment by modmuss50** [comment]
The change is fine, im just saying there is a better way to do the thing overall. (Prob out of scope for this PR)

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
