### PR TITLE
Map nd -> ConsoleCommandSender

### PR DESCRIPTION
**Pull request by maxpowa**
`net.minecraft.server.dedicated.ConsoleCommandSender`

Not really confident that `net.minecraft.server.dedicated` is the best package for this, but it's all I could find that really worked.

Maps two things from ICommandSender
`y_` -> `shouldOutput`
`a(Lnone/fa;)` -> `append(Lnone/fa;)`

### CODE REVIEW

**Comment by asiekierka** [comment]
I'm not entirely sure if the names are good. Thoughts?

**Comment by shadowfacts** [comment]
Is it used for the console or just rcon?

**Comment by maxpowa** [comment]
Console & Rcon, I'm open to name suggestions. I was questioning the package name in #fabric but nobody was around to provide input...

**Comment by maxpowa** [comment]
I'm on the fence about `append` now. `append` makes sense when something is only an ICommandSender impl, but when it's an ICommandSender impl and a bunch of other things it loses its meaning. Not sure what the best name is, but it definitely just appends the text component to the command buffer.

**Comment by asiekierka** [comment]
appendToCommandBuffer. We don't want conflicts with obvious names...

**Comment by maxpowa** [comment]
Actually wait, I think `appendToSenderBuffer` makes more sense than `appendToCommandBuffer`, because it's not actually appending to the command message itself, but the buffer which holds the responses. Going to change `clear` to `clearSenderBuffer` as well.

**Comment by asiekierka** [comment]
Sure

**Comment by maxpowa** [comment]
There we go, should be good now.

**Comment by asiekierka** [comment]
What is shouldOutput, by the way? I feel it might be something along the lines of shouldEchoSenderBuffer, or something.

**Pull request merged**
