### PR TITLE
[WIP] Figure out vanilla biome generation code

### PR DESCRIPTION
**Pull request by asiekierka**
These names are terrible, but I'm trying to figure things out. Discussion/advice welcomed.

### CODE REVIEW

**Comment by modmuss50** [comment]
Looks fine to me, might be a good idea to get @Prospector 's view on these names.

**Comment by shadowfacts** [comment]
The only issue I see is BiomeProvider vs BiomeProviderProvider (to say nothing of the tongue-twisting CachingBiomeProviderProvider). Are there other options for either of these?

**Comment by asiekierka** [comment]
The branch is an early WIP. The names are garbage, they really are. I'm just naming them whatever to try and figure out what the bundle of 30-40 classes with lots of lambdas does.

**Comment by asiekierka** [comment]
Taken over by #269

**Pull request closed without merging**
