### PR TITLE
client -> minecraft

### PR DESCRIPTION
**Pull request by shedaniel**
It is known that mojang uses `minecraft` other than `client` in classes like `Screen`

### CODE REVIEW

**Comment by liach** [comment]
Let's call it `client`. Newcomers may assume it is some sort of overall game instance that contains core logic like registries instead of the client when they see `minecraft`.

**Comment by shedaniel** [comment]
Newcomers will get confused when they mess with Screens anyways. If the newcomer only makes content mods, it is pretty rare that they will run into this mapping change as `client` mainly exists in the client side.

**Comment by Gegy** [comment]
I don't think "people will get confused anyway" is a great justification for a mappings change. Just because we can doesn't mean we should, imo.

**Comment by shedaniel** [comment]
That's true, but sometimes inconsistency can be confusing too. If I want to map this better, I would map minecraft -> client.

**Comment by liach** [comment]
Looking back into #66, it seems `Minecraft` as a noun is too vague about any component of the game, so we changed the `Minecraft` reference to `MinecraftGame` in #82 (Then to `MinecraftClient` in #220).

**Comment by shedaniel** [comment]
I will close this as this is not really a good idea

**Pull request closed without merging**
