### PR TITLE
fix inherited names not being mapped for AbstractNbtList

### PR DESCRIPTION
**Pull request by ghost**
theyre now mapped to the same name, it fixes issue

not sure why this was broken but it works now i think
also enigma refuses to save mappings from and to the same name so

### CODE REVIEW

**Comment by liach** [comment]
Is this a bug with the produced tiny mappings? If yes fixing the tiny mapping production in yarn would be better (for example, #2571 is broke because of the way tiny mappings are produced as of now)

**Comment by ghost** [comment]
yeah i think so cuz its not renaming methods with inherited mappings if the inherited names arent remapped if that makes sense

**Comment by liach** [comment]
Hmm, those methods are literally from `java.util.List`: [`void add(int, Object)`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#add-int-E-), [`Object remove(int)`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#remove-int-), and [`Object set(int, Object)`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#set-int-E-). And they do appear correct in the `decompileCfr` results.

What exact problem are you having? Broken name in mod development, or just red text in enigma?

**Comment by ghost** [comment]
when the mappings are generated for impl classes like NbtByteArray, it doesnt inherit those add remove set names. this is most likely intentional but it can cause issues as i found.
here is the merged reordered v2 mappings. left is latest published right is generated after this commit
image
on the right the names are correct, on the left they arent.

**Comment by ghost** [comment]
also decompilecfr might be wrong, the method names in NbtByteArray are fixed after this in the generated named jar

**Comment by liach** [comment]
Yeah, problem confirmed in decompilecfr, but this should be fixed in enigma/toolchain, as this is part of the problems with proper synthetic override name propagation. The tool should propagate the names from non-minecraft library classes as well.

**Comment by liach** [comment]
Namely, we call this name inheritance with with https://github.com/FabricMC/Enigma/blob/master/enigma-cli/src/main/java/cuchaz/enigma/command/MapSpecializedMethodsCommand.java (see #977). Probably need to check if https://github.com/FabricMC/Enigma/blob/master/enigma/src/main/java/cuchaz/enigma/analysis/index/BridgeMethodIndex.java has this bug.

**Comment by ghost** [comment]
yes. remapping the unobf name is not an ideal solution, a fix for the mappings generator needs to be found.

**Comment by ghost** [comment]
the changes this pr makes arent a good solution. moving this to an issue.

**Comment by ghost** [comment]
#2623

**Pull request closed without merging**
