### PR TITLE
client.util.math.Vector3f -> util.math.Vec3f

### LINKED ISSUE #978: Vector3f is in client.util.math
It's not client-only (as of 1.15-pre1).

### LINKED ISSUE #1716: Vec2f, Vec3d, Vector3f?
These names seem to be inconsistent. The fully named one is client only but that isn't a great naming standard. I feel in this case we need to consolidate these names in 1.17 snapshots

### PR DESCRIPTION
**Pull request by YanisBft**
Even though most of its methods are client only, Vector3f is not client only, so it has been moved to util.math. Also renamed to follow how the other vector classes are named there.
~~To be consistent with Vector3f, the other vector classes were renamed to Vector* instead of Vec*.~~

Closes #978 and closes #1716 

Also fixed invalid mappings and updates Enigma

### CODE REVIEW

**Comment by Player3324** [comment]
It'd be more in line with the conventions to fix the abbreviations?

**Comment by YanisBft** [comment]
wdym?

**Comment by Juuxel** [comment]
Isn't `Vector3f` mutable unlike the `util.math.Vec*`s? That should be in its name IMO.

**Comment by Player3324** [comment]
Yarn generally favors the long form. While we already have some uses of "vec", "vector" is used often enough and matches Matrix 

The (im)mutability is probably not worth mentioning. If you look at Vec3i, it's all inconsistent... Vec3i even has an `@Unmodifiable` annotation, but that's a lie for at least some sub-classes.. Currently only Vec2f and Vec3d are properly immutable, the other vectors and matrices are not.

**Comment by YanisBft** [comment]
I agree, doesn't need to specify the immutability.

Regarding the abbreviation, I think "Vec" is clear enough, but if people prefer to use "Vector", I'll rename the 4 vector classes in the package

**Comment by Player3324** [comment]
<https://github.com/FabricMC/yarn/search?q=vec> has a few locations where vector would fit better IMO, e.g getRotationVec (vs getRotVec / getRotationVector) or all the "vec" arg names. It is a little weird to go there, but not Matrix (Mat), Rotation (Rot), Direction (Dir), ...

The 2/3/4 i/d suffixes make it less bad, not sure what the community wants at large

**Comment by Earthcomputer** [comment]
Disagree with lengthening the other class names. The abbreviations are so common that they are pretty standard. Also, would you be in favour of lengthening `BlockPos` to `BlockPosition`? I'd think not.
I agree that the method names you mentioned should be lengthened.

As for this PR, this vector class is clearly meant for client-side use so that needs to be preserved somewhere. It's unfortunate that the package needs to change, so maybe in the documentation? Agree with Juuxel that this could be renamed to `MutableVec3f`.

**Comment by Runemoro** [comment]
I agree with Player about preferring not using abbreviations. It's easier to read text that isn't full of abbreviations, and likely not slower to type since your IDE will auto-complete it anyway.

**Comment by YanisBft** [comment]
Renamed the Vec* classes to Vector*

**Review by Runemoro — APPROVED** [review]

**Comment by i509VCB** [comment]
Could the issue name have that included so people see what is happening from a glance?

**Review by i509VCB — APPROVED** [review]

**Review by Gegy — APPROVED** [review]

**Review by Juuxel — CHANGES_REQUESTED** [review]
Both `Vec` and `Vector` are fine, but the mutability should be in `class_1160`'s name. (Regarding `Vector3i`'s "immutability": even though it's internally mutable, it doesn't expose mutating methods publically)

**Comment by YanisBft** [comment]
I don't get why mutability should be included in the name, at least when there is no immutable class it could be confused with. Adding `Mutable` as a prefix just makes the class both harder to find in class tree and via autocompletion

**Comment by Juuxel** [comment]
There are already immutable/unmodifiable classes that follow the `Vec*` (or `Vector*`) pattern, which makes users expect that all `Vector*`s are unmodifiable, even though `Vector3f` is not.

**Comment by Player3324** [comment]
Vector3i expresses no (im)mutability, it is internally mutable and its users can **not** expect it to stay the same, much like List. It isn't worth qualifying auxiliary properties if there's only one implemented variant. When a property like mutability changes within a type hierarchy, the base class needs to be the unqualified one.

**Comment by Juuxel** [comment]
Sure enough. I would still add a small line of javadoc to each vector specifying whether it's publically mutable (`3f` and other client vectors), publically read-only but actually mutable (`3i`) or actually immutable.

**Review by Juuxel — APPROVED** [review]

**Review by jaskarth — APPROVED** [review]

**Review by dblsaiko — APPROVED** [review]

**Review by dexman545 — APPROVED** [review]
I agree that using abbreviations in class names are fine

**Review by Player3324 — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
